name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Install Capacitor
        run: |
          npm install @capacitor/core
          npm install @capacitor/cli
          npm install @capacitor/android

      - name: Create Android project
        run: |
          npx cap init app com.app.test --web-dir=dist
          npx cap add android
          npx cap copy

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Rename APK
        run: |
          mv android/app/build/outputs/apk/debug/app-debug.apk ${{ github.event.repository.name }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ github.event.repository.name }}.apk
